services: 

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - decoviz_common_default

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - decoviz_common_default

  flower:
    build:
      context: .
      dockerfile: common/Dockerfile
    container_name: flower
    restart: always
    env_file:
      - .env
    environment:
      - FLOWER_BASIC_AUTH=${FLOWER_USERNAME}:${FLOWER_PASSWORD} 
      - FLOWER_BROKER=${REDIS_URL}
    ports:
      - "5555:5555"
    networks:
      - decoviz_common_default
    depends_on:
      - celery_worker
      - redis
    command: >
      bash -c "pip install flower &&
      celery -A deckoviz flower --port=5555 --broker=${REDIS_URL}"

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: common/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    volumes:
      - ./logs/celery:/app/logs/celery 
    networks:
      - decoviz_common_default
    command: ["/usr/bin/supervisord"]

  common:
    build:
      context: .
      dockerfile: common/Dockerfile
    image: common:latest
    container_name: common
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./common:/app
      - ./logs:/app/logs  # Mount logs directory
    command: ["bash", "/app/scripts.sh"]
    depends_on:
      - redis
      - postgres
    networks:
      - decoviz_common_default 

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - ./api/.env
    image: api:latest
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      - redis
      - postgres
    networks:
      - decoviz_common_default
    volumes:
      - ./api:/app
      - ./logs:/app/logs  # Mount logs directory
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/" , "||" , "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  decoviz_common_default: 
    driver: bridge

volumes:
  redis_data:
  postgres_data:
